ALTER ROLE [db_datawriter] ADD MEMBER [BRIGHTSTAR\RMurugappan];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_TMA_PLM];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_DBA_S];


GO
ALTER ROLE [db_datawriter] ADD MEMBER [BRIGHTSTAR\RMurugappan];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_TMA_PLM];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_DBA_S];


GO
ALTER ROLE [db_datawriter] ADD MEMBER [BRIGHTSTAR\RMurugappan];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_TMA_PLM];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_DBA_S];


GO
ALTER ROLE [db_datawriter] ADD MEMBER [BRIGHTSTAR\RMurugappan];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_TMA_PLM];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_DBA_S];


GO
ALTER ROLE [db_datawriter] ADD MEMBER [BRIGHTSTAR\RMurugappan];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_TMA_PLM];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_DBA_S];


GO
ALTER ROLE [db_datawriter] ADD MEMBER [BRIGHTSTAR\RMurugappan];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_TMA_PLM];


GO
ALTER ROLE [db_datareader] ADD MEMBER [BRIGHTSTAR\APACDB_DBA_S];

